development:
  password: 38408cab4b5fd31cdf04b884592f29cf
  theme_id: "32159301717"
  store: mille-fryd-knitwear.myshopify.com
dk:
  password: 38408cab4b5fd31cdf04b884592f29cf
  theme_id: "32159301717"
  store: mille-fryd-knitwear.myshopify.com
